[build-system]
requires = ["setuptools>=66.0"]
build-backend = "setuptools.build_meta"

[project]
name = "a_maze_ing"
version = "0.1.0"
requires-python = ">=3.8"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["src"]
include = ["src"]